#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals

import sys
from math import *
from random import *

from calca_utils import *

def main():
    fun = eval(sys.argv[1])
    ev = Evaler()
    for line in sys.stdin:
        val = ev(line)
        try:
            cond = fun(*val)
        except TypeError:
            cond = fun(val)
        if cond:
            sys.stdout.write(line)
    return 0

if __name__ == '__main__':
    sys.exit(main())
